vagrant/README.md
add traffic permission for kong service
=> docs: traffic permission for kong

vagrant/prometheus/app/prometheus.yaml
* remove `refresh_interval` from the example Prometheus configuration (feedback from Prometheus maintainers)
=> docs: remove `refresh_interval` from the example Prometheus configuration (feedback from Prometheus maintainers)

README.md, api/README.md, api/db/docker-elasticsearch-kubernetes/do_not_use.yml, app/README.md, kubernetes/README.md, kubernetes/kuma-demo-log.yaml
Update the repository to be easier to navigate
=> update project structure/docs

vagrant/README.md, vagrant/kong/app/config/config.yaml
* [Implement ...]
* [Fix ...]
Fix #XXX
=> docs: update vagrant setup

vagrant/README.md
* [Implement ...]
* [Fix ...]
Fix #XXX
=> docs: update link

kubernetes/README.md, kubernetes/kuma-demo-log.yaml
Merge after releasing the version with fix of adding \n char
=> fix: logging to loggly with json_lines

api/app/elastic.js, api/index.js, kubernetes/kuma-demo-aio.yaml
Coop with @devadvocado 
Please remember to publish a new version of the docker image after merge.
=> Pass predefined tracing headers from API to elastic

kubernetes/README.md
I have updated the docs to 0.4.0 (and tested it with that version on my machine)
All references to new version
Confusion on versions for testers / users
=> Updated to Kuma 0.4.0

api/index.js, api/package-lock.json, api/package.json
Adds simple Prometheus metrics to API application so we can present scraping from app and Envoy. Metrics are available on `127.0.0.1:9991/metrics`
=> API metrics

kubernetes/README.md, kubernetes/kuma-demo-jaeger.yaml
Updating Kubernetes demo to be compatible with the new version of Kuma v0.5.0
=> fix: update kubernetes demo for 0.5.0 version

api/index.js, api/package-lock.json, api/package.json
api-express-exporter broke Demo in a couple of places. Changed to expres-prom-bundle.
=> api metrics using express-prom-bundle

kind/README.md, kind/cluster.yaml, kind/kind.sh, kubernetes/README.md
Signed-off-by: Nikolay Nikolaev <nikolay.nikolaev@konghq.com>
Add kind deployment folder for easier demonstration of Kuma.
A script to implement a step by step deployment of Kuma and the Demo.
Provide a lightweight deployment option for exploring Kuma.
* Adds the kind folder with the script and the kind cluster configuration
=> Add kind demo deployment

kubernetes/README.md
Small docs fix
Adds `EOF` marker
Broken script
N/A
N/A
=> docs: add EOF for TraffiHealthCheckcRoute

kubernetes/README.md, kubernetes/kuma-demo-aio.yaml, vagrant/Vagrantfile
* [Implement ...]
* [Fix ...]
Fix #XXX
=> update demo for v0.7.0

kubernetes/README.md
service tag is prefixed with `kuma.io/`
=> fix(*) fix tags on the demo

vagrant/README.md, vagrant/backend-v1/kuma/dataplane.yaml, vagrant/backend/kuma/dataplane.yaml, vagrant/frontend/kuma/dataplane.yaml, vagrant/kong/kuma/dataplane.yaml, vagrant/redis/kuma/dataplane.yaml
`skipMTLS: true` and prefix builtin tags with `kuma.io/`
=> update universal demo to 0.7.0

vagrant/README.md, vagrant/Vagrantfile, vagrant/postgresql/kuma/dataplane.yaml
- Update Kuma to 0.7.1
- Update Ubuntu box to 1.18 to support Envoy 1.15
- Add one missing service tag
=> chore: update to 0.7.1

kubernetes/README.md
Bumping the Kubernetes demo to use Kuma 1.0.0
=> docs: bump to 1.0.0 for k8s

vagrant/README.md, vagrant/Vagrantfile, vagrant/backend-v1/kuma/kuma-dp.service, vagrant/backend/kuma/kuma-dp.service, vagrant/common/install_kuma-dp.sh, vagrant/control-plane/kuma/create_dp_tokens.sh, vagrant/control-plane/kuma/kuma-cp.service, vagrant/frontend/kuma/kuma-dp.service, vagrant/kong/kuma/kuma-dp.service, vagrant/metrics/kuma/kuma-prometheus-sd.service, vagrant/postgresql/kuma/kuma-dp.service, vagrant/redis/kuma/kuma-dp.service
Update kuma-demo universal instructions to work with latest version of Kuma 1.0.3
=> chore: bump to 1.0.3

vagrant/Vagrantfile, vagrant/common/download_kuma.sh
This fixes #121.
Signed-off-by: James Peach <james.peach@konghq.com>
=> fix(vagrant) default to installing latest Kuma

kind/kind.sh
* The hard-coded Kuma version was ancient, so stop hard-coding it and
use the online installation script to default to installing the latest
version.
* Fix the face condition waiting for Kubernetes deployments to succeed.
* Fix the Kuma GUI link and port forwarding.
* Upgrade to the latest version of Kind.
This fixes #124.
=> fix(*) various kind cluster bringup bugs

vagrant/control-plane/kuma/create_tls_cert.sh, vagrant/postgresql/app/start.sh
Fix vagrant configuration
Did you sign your commit? [Instructions](https://github.com/kumahq/.github/blob/main/CONTRIBUTING.md#sign-your-commits): 👍 
Have you read [Contributing guidelines](https://github.com/kumahq/.github/blob/main/CONTRIBUTING.md)?: 👍
=> fix: fix vagrant setup

README.md
<Explain your change!>
Did you sign your commit? [Instructions](https://github.com/kumahq/.github/blob/main/CONTRIBUTING.md#sign-your-commits)
Have you read [Contributing guidelines](https://github.com/kumahq/.github/blob/main/CONTRIBUTING.md)?
=> docs(links): fix chat link

kubernetes/kuma-demo-aio.yaml
Converts all endpoints to `.mesh` addresses and ports so the demo works out-of-the-box in multi-zone mode.
=> feat(demo): change all endpoints to .mesh
